language: c

compiler:
  - clang
  - gcc

script:
  - env | sort
  - mkdir -vp build
  - cd build
  - autoreconf -ivf ..
  - ../configure --prefix=${HOME}
  - make
  - make distcheck
  - make install

